import src.files.file_utils as file_utils


NAME_FOLDER_TEMPLATES = "Templates"
DEFAULT_BASE_FOLDER_TEMPLATES = file_utils.concat_folder_filename(
    ".", NAME_FOLDER_TEMPLATES)

JINJA_FILE_EXTENSION = "jinja"

# Solidity

FOLDERS_PATH_INPUT_SOLIDITY = "solidity"
FOLDERS_PATH_OUTPUT_SOLIDITY = FOLDERS_PATH_INPUT_SOLIDITY

SOLIDITY_VERSION_DEFAULT = "^0.8.0"

NAME_FOLDER_TEMPLATES_VOTING_PROTOCOL = "voting_protocols"
DEFAULT_FOLDER_TEMPLATES_VOTING_PROTOCOL = file_utils.concat_folder_filename(
    DEFAULT_BASE_FOLDER_TEMPLATES, NAME_FOLDER_TEMPLATES_VOTING_PROTOCOL)

NAME_FOLDER_TEMPLATES_INTERFACES = "interfaces"
DEFAULT_FOLDER_TEMPLATES_INTERFACES = file_utils.concat_folder_filename(
    DEFAULT_BASE_FOLDER_TEMPLATES, NAME_FOLDER_TEMPLATES_INTERFACES)

# ASM

FOLDERS_PATH_INPUT_ASM = "asm"
FOLDERS_PATH_OUTPUT_ASM = FOLDERS_PATH_INPUT_ASM
ASM_FILE_EXTENSION = "asm"

# Solidity Hardhat Tests

TESTS_FILE_EXTENSION = "js"
FOLDERS_PATH_INPUT_SOLIDITY_TEST = "test_scripts"
FOLDERS_PATH_OUTPUT_SOLIDITY_TEST = file_utils.concat_folder_filename(
    FOLDERS_PATH_INPUT_SOLIDITY, "tests")

# Petri Nets
# TODO
