import src.files.file_utils as file_utils


NAME_FOLDER_TEMPLATES = "Templates"
DEFAULT_BASE_FOLDER_TEMPLATES = file_utils.concat_folder_filename(
    ".", NAME_FOLDER_TEMPLATES)

JINJA_FILE_EXTENSION = "jinja"

# Solidity

FOLDER_NAME_SOLIDITY = "solidity"

SOLIDITY_VERSION_DEFAULT = "^0.8.0"

NAME_FOLDER_TEMPLATES_VOTING_PROTOCOL = "voting_protocols"
DEFAULT_FOLDER_TEMPLATES_VOTING_PROTOCOL = file_utils.concat_folder_filename(
    DEFAULT_BASE_FOLDER_TEMPLATES, NAME_FOLDER_TEMPLATES_VOTING_PROTOCOL)

NAME_FOLDER_TEMPLATES_INTERFACES = "interfaces"
DEFAULT_FOLDER_TEMPLATES_INTERFACES = file_utils.concat_folder_filename(
    DEFAULT_BASE_FOLDER_TEMPLATES, NAME_FOLDER_TEMPLATES_INTERFACES)

# ASM

FOLDER_NAME_ASM = "asm"
ASM_FILE_EXTENSION = "asm"

# HardhatTests

TESTS_FILE_EXTENSION = "js"
FOLDER_NAME_TESTS = file_utils.concat_folder_filename(
    FOLDER_NAME_SOLIDITY, "tests")

# Petri Nets
# TODO
